apiVersion: apps/v1
kind: Deployment
metadata:
  name: yncrea-demo
spec:
  selector:
    matchLabels:
      app: yncrea-demo
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: yncrea-demo
    spec:
      containers:
      - name: yncrea
        image: ghcr.io/pierrez/cloud-computing-101:main
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
 name: my-api-service
spec:
 ports:
 - port: 80
   protocol: TCP
   targetPort: 8080
 selector:
   app: yncrea-demo
 type: NodePort